export const TAURI_EVENT_UPDATE_APPDATA = "update-appdata"
export const TAURI_COMMAND_HEALTH_CHECK = "get_health_check"
export const TAURI_COMMAND_STATUS = "get_status"
export const TAURI_COMMAND_INIT = "post_init"
export const TAURI_COMMAND_RESET = "post_reset"